services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    networks:
      - taxi_net
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dispatch:
    build:
      context: ./dispatch
    image: dispatch:latest
    container_name: dispatch
    environment:
      POSTGRES_HOST: "postgres"
    volumes:
      - ./dispatch/alembic:/app/alembic:rw
    ports:
      - "8080:8080"
    networks:
      - taxi_net
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  taxi:
    build:
      context: ./taxi
    image: taxi:latest
    container_name: taxi
    networks:
      - taxi_net
    environment:
      DISPATCH_URL: http://dispatch:8080
    env_file:
      - .env
    depends_on:
      - dispatch

  traffic:
    build:
      context: ./traffic_generator
    image: traffic:latest
    container_name: traffic
    networks:
      - taxi_net
    environment:
      DISPATCH_URL: http://dispatch:8080
    env_file:
      - .env
    depends_on:
      - dispatch

volumes:
  postgres_data:

networks:
  taxi_net:
    external: true
