services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    restart: always
    networks:
      - taxi_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dispatch:
    build:
      context: ./dispatch
    image: dispatch:latest
    container_name: dispatch
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/testdb
    volumes:
      - ./dispatch/alembic:/app/alembic:rw
    ports:
      - "8080:8080"
    networks:
      - taxi_net
    depends_on:
      postgres:
        condition: service_healthy

  taxi:
    build:
      context: ./taxi
    image: taxi:latest
    container_name: taxi
    networks:
      - taxi_net
    environment:
      DISPATCH_URL: http://dispatch:8080
    depends_on:
      - dispatch

volumes:
  postgres_data:

networks:
  taxi_net:
    external: true
