"""add taxi_id to trip table

Revision ID: 0001
Revises: 0000
Create Date: 2025-05-20 19:34:36.129505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = '0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('taxi_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'trip', 'taxi', ['taxi_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'taxi_id')
    # ### end Alembic commands ###
